# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
 name: 'Default'
 demands:
  - SDE32
  - SDE64
  - SDI
  - WIX

variables:
  solution: 'CodeGen.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  agent.retainDefaultEncoding: true

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: BatchScript@1
  displayName: 'Profile Environment'
  inputs:
    filename: '$(SYNERGYDE32)\dbl\dblvars32.bat'
    arguments: 
    modifyEnvironment: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  name: cert # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: 63ee1fbd-46e2-49cc-abcc-f7cf5eeec575

- task: CmdLine@2
  inputs:
    script: 'signtool sign /v /td sha256 /tr http://timestamp.digicert.com /fd sha256 /f $(cert.secureFilePath) /p "$(SigPass)" /d "CodeGen" /du "www.synergex.com" bin\release\CodeGen.msi'