# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
 name: 'Default'
 demands:
  - SDE32
  - SDE64
  - SDI
  - WIX

variables:
- group: Secure
- name: solution
  value: 'CodeGen.sln'
- name: installerProj
  value: 'CodeGenSetup\\CodeGenSetup.wixproj'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: BatchScript@1
  displayName: 'Profile Environment'
  inputs:
    filename: '$(SYNERGYDE32)\dbl\dblvars32.bat'
    arguments: 
    modifyEnvironment: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '$(installerProj)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:SolutionDir=$(Agent.BuildDirectory)\\'

- task: DownloadSecureFile@1
  name: cert
  inputs:
    secureFile: 63ee1fbd-46e2-49cc-abcc-f7cf5eeec575

- task: CmdLine@2
  inputs:
    script: '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\signtool.exe" sign /v /td sha256 /tr http://timestamp.digicert.com /fd sha256 /f $(cert.secureFilePath) /p "$(SigPass)" /d "CodeGen" /du "www.synergex.com" bin\release\CodeGen.msi'

# Publish build artifacts to Azure Pipelines or a Windows file share
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'bin\release\CodeGen.msi' 
    artifactName: 'CodeGen-Installer' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    #fileCopyOptions: #Optional